language: java
cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - mvn package -DskipDocker=False
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: .onejar/target/pwm-onejar-1.8.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: silentdark/pwm
branches:
  only:
    - master
  
