language: java
before_install:
  - nvm install 'lts/*'
  - npm install –g @angular/cli
  - npm install
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.npm
script:
  - mvn clean package
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: .onejar/target/pwm-onejar.jar
  skip_cleanup: true
  on:
    repo: silentdark/pwm
    tags: true
branches:
  only:
    - uat  