language: java
script:
  - mvn package -DskipDocker=False
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ./docker/target/jib-image.tar
  skip_cleanup: true
  on:
    repo: silentdark/pwm
branches:
  only:
    - master
